import type { RankedMatch } from "./matching";
import type { Profile } from "./state";

/** Minimal AI re-ranker prototype.
 *
 * Important: this is an advisory layer only. It never alters the deterministic
 * `checks` or `tone` computed by `lib/logic/matching.ts` — it only reorders
 * the deterministic outputs for presentation and attaches short explanations.
 */

export type AiConfidence = "High" | "Medium" | "Low";

export interface AiExplanation {
  id: string;
  reason: string;
  confidence: AiConfidence;
  sources?: string[];
}

export interface AiReRankResult {
  reRanked: RankedMatch[];
  explanations: AiExplanation[];
}

/** Feature gate — replace with env flag or runtime config as needed. */
export function aiEnabled(): boolean {
  return !!process.env.NEXT_PUBLIC_AI_MATCHING_ENABLED;
}

/**
 * A tiny mock re-ranker used for prototyping and tests. It prefers higher
 * `tone` (strong->good->possible->none) and, within the same tone, larger
 * `met/total` ratio and amount is used by the deterministic engine; this
 * function demonstrates an advisory reorder and generates short reasons.
 */
export async function aiReRank(
  ranked: RankedMatch[],
  _profile: Profile
): Promise<AiReRankResult> {
  // If AI feature is disabled, return the deterministic ordering with
  // autogenerated explanations that mirror the deterministic facts.
  const explanations: AiExplanation[] = ranked.map((r) => ({
    id: r.id,
    reason: `${r.match} — ${r.met}/${r.total} published requirements met.`,
    confidence: r.tone === "strong" ? "High" : r.tone === "good" ? "Medium" : "Low",
  }));

  // Simple advisory reordering: keep the list as-is for now. A real adapter
  // would call an LLM with a structured prompt and return a validated JSON.
  return { reRanked: ranked.slice(), explanations };
}

export default aiReRank;
