import type { RankedMatch } from "./matching";
import type { Profile } from "./state";
import type { Language } from "./locale";

export interface AiExplanation {
  id: string;
  reason: string;
}

export interface AiReRankResult {
  /** Kept for compatibility; the server never changes deterministic ordering. */
  reRanked: RankedMatch[];
  explanations: AiExplanation[];
  /** True only when the explanation was generated by the configured AI provider. */
  generated: boolean;
}

export function aiEnabled(): boolean { return true; }

export async function aiReRank(ranked: RankedMatch[], _profile?: Profile, language: Language = "ENG"): Promise<AiReRankResult> {
  void _profile;
  const fallback = ranked.map((match) => ({
    id: match.id,
    reason: `${match.match} — ${match.met} of ${match.total} published requirements matched${match.unknown ? `; ${match.unknown} to confirm` : ""}.`,
  }));
  try {
    const res = await fetch("/api/ai/rerank", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rankedMatches: ranked, language }) });
    if (res.ok) {
      const json = (await res.json()) as AiReRankResult;
      if (Array.isArray(json.explanations)) {
        return {
          reRanked: ranked,
          explanations: json.explanations,
          generated: json.generated === true,
        };
      }
    }
  } catch { /* deterministic fallback */ }
  return { reRanked: ranked, explanations: fallback, generated: false };
}
